### ISSUE TITLE
Cannot read property 'executeScript' of undefined

### ISSUE THREAD

**Issue by elgubenis** [samccone/drool#10]
i guess im doing something wrong with the webdriver

```sh
TypeError: Cannot read property 'executeScript' of undefined
  at getCounts (/Users/lgubenis/projects/paper/node_modules/drool/lib/index.js:14:9)
  at Object.flow (/Users/lgubenis/projects/paper/node_modules/drool/lib/index.js:39:3)
  at Object.<anonymous> (/Users/lgubenis/projects/paper/test/index.coffee:7:7)
  at Object.<anonymous> (/Users/lgubenis/projects/paper/test/index.coffee:1:1)
  at Module._compile (module.js:460:26)
```

**Comment by elgubenis** [comment]
```coffee
drool = require('drool')
assert = require('assert')

driver = drool.start
  chromeOptions: 'no-sandbox'

drool.flow
  repeatCount: 100
  setup: ->
    driver.get('http://localhost:3000')
  action: ->

    # click on add page
    # adds page
    driver.findElement(
      drool.webdriver.By.css('#drool-add-page')
    ).click()

    # click on page
    # opens menu for page
    driver.findElement(
      drool.webdriver.By.css('.page')
    ).click()

    # click on delete
    driver.findElement(
      drool.webdriver.By.css('.drool-delete-page')
    ).click()
  asset: (after, initial) ->
    assert.equal(inital.nodes, after.nodes, 'node count should match')

driver.quit()
```

**Comment by samccone** [comment]
Easy fix :+1: 
```diff
- drool.flow
+ drool.flow({
  repeatCount: 100
  setup: ->
    driver.get('http://localhost:3000')
  action: ->

    # click on add page
    # adds page
    driver.findElement(
      drool.webdriver.By.css('#drool-add-page')
    ).click()

    # click on page
    # opens menu for page
    driver.findElement(
      drool.webdriver.By.css('.page')
    ).click()

    # click on delete
    driver.findElement(
      drool.webdriver.By.css('.drool-delete-page')
    ).click()
  asset: (after, initial) ->
    assert.equal(inital.nodes, after.nodes, 'node count should match')
+ }, driver)
```

**Comment by elgubenis** [comment]
whoops, kthxbye :+1:

**Comment by samccone** [comment]
no problem @elgubenis :+1: 

I agree that the error is super confusing :question: 

Let me know if you have any other questions

**Comment by elgubenis** [comment]
yeah, i've got more questions, do you want them here or in another issue (i think its unrelated to this issue)

**Comment by samccone** [comment]
another issue is fine :)
