### ISSUE TITLE
Doesn't work with chromedriver v >= 2.29

### ISSUE THREAD

**Issue by artemv** [samccone/drool#32]
It doesn't detect leaks starting with chromedriver v 2.29 (checked with 2.30 and 2.31 too - same thing) - at least as per tests. Check Travis builds:
* https://travis-ci.org/samccone/drool/builds/265281129 pass, this is for 2.28
* https://travis-ci.org/samccone/drool/builds/265281467 fail, this is for 2.29

Looks like this is because drool don't get counts data starting from 2.29, https://github.com/samccone/drool/commit/cd4614df7922cb3f9aebb7bbcde11dcf59154024 kinda hides this issue - drool doesn't error in this case but becomes useless. If NPM published version 0.4.0 is used it errors instead:
```
TypeError: Cannot read property 'message' of undefined
    at /my/project/path/node_modules/drool/lib/index.js:40:27
    at ManagedPromise.invokeCallback_ (/my/project/path/node_modules/selenium-webdriver/lib/promise.js:1343:14)
    at TaskQueue.execute_ (/my/project/path/node_modules/selenium-webdriver/lib/promise.js:2868:14)
    at TaskQueue.executeNext_ (/my/project/path/node_modules/selenium-webdriver/lib/promise.js:2851:21)
    at asyncRun (/my/project/path/node_modules/selenium-webdriver/lib/promise.js:2730:27)
    at /my/project/path/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by artemv** [comment]
Note that it works with chromedriver-helper 2.28

**Comment by artemv** [comment]
strange, after some experimenting this error went away and now I'm able to run it with chromedriver 2.31 - not sure what helped. closing.

**Comment by artemv** [comment]
However it doesn't seem to detect leaks properly with chromedriver 2.29+ as per tests - will update the description.
